version: '3'

services:
 
  mail-db:
    container_name: mail-db
    build:
      context: ./Maildata
      dockerfile: Dockerfile

      
  mail-service:
    container_name: mail-service
    build:
      context: ./app
      dockerfile: Dockerfile


