version: '3'

services:
  
  configurator-service:
    extends:
      file: ConfiguratorService/docker-compose.yml
      service: configurator-service
      
  configurator-db:
    extends:
      file: ConfiguratorService/docker-compose.yml
      service: configurator-db
   
  mail-service:
    extends:
      file: MailService/docker-compose.yml
      service: mail-service
      
  mail-db:
    extends:
      file: MailService/docker-compose.yml
      service: mail-db
  
      
  notifier-service:
    extends:
      file: NotifierService/docker-compose.yml
      service: notifier-service

      
  notifier-db:
    extends:
      file: NotifierService/docker-compose.yml
      service: notifier-db
      
  scheduler-service:
    extends:
      file: SchedulerService/docker-compose.yml
      service: scheduler-service
      
  scheduler-db:
    extends:
      file: SchedulerService/docker-compose.yml
      service: scheduler-db
      
  telegram-service:
    extends:
      file: TelegramService/docker-compose.yml
      service: telegram-service
      
  telegram-db:
    extends:
      file: TelegramService/docker-compose.yml
      service: telegram-db
      
  weather-service:
    extends:
      file: WeatherService/docker-compose.yml
      service: weather-service
      
  weather-db:
    extends:
      file: WeatherService/docker-compose.yml
      service: weather-db
      
      
volumes:
  configurator-database:  
    name: configurator-database
  mail-database:  
    name: mail-database
  telegram-database:  
    name: telegram-database
  notifier-database:
    name: notifier-database
  weather-database:  
    name: weather-database
  scheduler-database:  
    name: scheduler-database



