version: '3'

services:
 
  weather-db:
    container_name: weather-db
    build:
      context: ./Weatherdata
      dockerfile: Dockerfile


  weather-service:
    container_name: weather-service
    build:
      context: ./app
      dockerfile: Dockerfile

      
