---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'expose-api'
        scrape_interval: 5s 
        static_configs:
          - targets: ['expose-api:8080']
        tls_config:
          insecure_skip_verify: true

---