---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: weather-service-part0
  name: weather-service-part0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weather-service-part0
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/microservices-network: "true"
        io.kompose.service: weather-service-part0
    spec:
      containers:
        - env:
            - name: CONSUMER_AUTO_OFFSET_RESET
              value: earliest
            - name: CONSUMER_BOOTSTRAP_SERVERS
              value: kafka:9093
            - name: CONSUMER_GROUP_ID
              value: WeatherService
            - name: DATABASE_IP
              value: weather-db
            - name: DATABASE_NAME
              value: Weather
            - name: DATABASE_PASSWORD
              value: root
            - name: DATABASE_PORTA
              value: "3312"
            - name: DATABASE_USERNAME
              value: root
            - name: DISTANCE_REUSE_WEATHER_KM
              value: "5"
            - name: DOCKER_ENVIRONMENT
              value: "True"
            - name: GROUP_ID
              value: WeatherService
            - name: HEARTBEAT_FREQUENCY
              value: "10"
            - name: PARTITION
              value: "0"
            - name: PRODUCER_BOOTSTRAP_SERVERS
              value: kafka:9093
            - name: PRODUCER_CLIENT_ID
              value: WeatherService
            - name: SLAMANAGER
              value: sla-manager
          image: mircoantona/weathereventnotifier:weather-service-part0
          name: weather-service-part0
          ports:
            - containerPort: 8089
              hostPort: 8089
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: "226492416"
      restartPolicy: Always
status: {}

---
