version: '3'

services:
    
  configurator-db:
    container_name: configurator-db
    build:
      context: ./Configuratordata
      dockerfile: Dockerfile

      
  configurator-service:
    container_name: configurator-service
    build:
     context: ./app
     dockerfile: Dockerfile


