version: '3'

services:
    
  configurator_db:
    container_name: configurator_db
    build:
      context: ./Configuratordata
      dockerfile: Dockerfile
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - configurator_database:/var/lib/mysql
    networks:
      - microservices_network
      
  configurator_service:
    container_name: configurator_service
    build:
     context: ./app
     dockerfile: Dockerfile
    environment:
     - DOCKER_ENVIRONMENT=True
     - DATABASE_USERNAME=root
     - DATABASE_PASSWORD=root
     - DATABASE_PORTA=3306
     - DATABASE_IP=configurator_db
     - DATABASE_NAME=ConfigurationAlert 
    networks:
      - microservices_network 
    depends_on:
      - configurator_db      

volumes:
  configurator_database:  
    name: configurator_database
networks:
  microservices_network:
    name: microservices_network
