version: '3'

services:
    
  telegram-db:
    container_name: telegram-db
    build:
      context: ./Telegramdata
      dockerfile: Dockerfile
      
  telegram-service:
    container_name: telegram-service
    build:
      context: ./app
      dockerfile: Dockerfile
