version: '3'

services:
  scheduler-db:
    container_name: scheduler-db
    build:
      context: ./Schedulerdata
      dockerfile: Dockerfile

      
  scheduler-service:
    container_name: scheduler-service
    build:
      context: ./app
      dockerfile: Dockerfile

