version: '3'

services:
    
  notifier_db:
    container_name: notifier_db
    build:
      context: ./Notifierdata
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - notifier_database:/var/lib/mysql
    networks:
      - microservices_network

  notifier_service:
    container_name: notifier_service  
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
     - DOCKER_ENVIRONMENT=True
     - DATABASE_USERNAME=root
     - DATABASE_PASSWORD=root
     - DATABASE_PORTA=3306
     - DATABASE_IP=notifier_db
     - DATABASE_NAME=Notifier
    networks:
      - microservices_network 
    depends_on:
      - notifier_db    

volumes:
  notifier_database:  
    name: notifier_database
networks:
  microservices_network:
    name: microservices_network
