version: '3'

services:
    
  notifier-db:
    container_name: notifier-db
    build:
      context: ./Notifierdata
      dockerfile: Dockerfile

  notifier-service:
    container_name: notifier-service
    build:
      context: ./app
      dockerfile: Dockerfile

