---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: configurator-db
  name: configurator-db
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3306
  selector:
    io.kompose.service: configurator-db
status:
  loadBalancer: {}

---
