---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: configurator-service-cluster0-part0
  name: configurator-service-cluster0-part0
spec:
  ports:
    - name: "8084"
      port: 8084
      targetPort: 8084
  selector:
    app.service: configurator-service-cluster0-part0
status:
  loadBalancer: {}

---
