---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: forecast-service
  name: forecast-service
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  selector:
    app.service: forecast-service
status:
  loadBalancer: {}

---