apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana  
        app.network/microservices-network: "true"
        app.service: grafana
    spec:
      containers:
        - env:
            - name: GF_INSTALL_PLUGINS
              value: grafana-piechart-panel,grafana-worldmap-panel,vertamedia-clickhouse-datasource
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: admin
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_USERS_DEFAULT_THEME
              value: light
          image: grafana/grafana
          name: grafana-service
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: '108M'
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-pv-volume
      volumes:
        - name: grafana-pv-volume
          persistentVolumeClaim:
            claimName: grafana-pvc
