---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka0
  name: kafka0
spec:
  ports:
    - name: "9093"
      port: 9093
      targetPort: 9093
  selector:
    io.kompose.service: kafka0
status:
  loadBalancer: {}

---