---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: mail-db
  name: mail-db
spec:
  ports:
    - name: "3308"
      port: 3308
      targetPort: 3306
  selector:
    app.service: mail-db
status:
  loadBalancer: {}

---