---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: mail-service-cluster0-part0
  name: mail-service-cluster0-part0
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
  selector:
    app.service: mail-service-cluster0-part0
status:
  loadBalancer: {}

---