---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: notifier-service-cluster0-part0
  name: notifier-service-cluster0-part0
spec:
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
  selector:
    app.service: notifier-service-cluster0-part0
status:
  loadBalancer: {}

---