---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: notifier-db
  name: notifier-db
spec:
  ports:
    - name: "3309"
      port: 3309
      targetPort: 3306
  selector:
    app.service: notifier-db
status:
  loadBalancer: {}

---