---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: notifier-service-cluster0-part0
  name: notifier-service-cluster0-part0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: notifier-service-cluster0-part0
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/microservices-network: "true"
        io.kompose.service: notifier-service-cluster0-part0
    spec:
      containers:
        - env:
            - name: CONSUMER_AUTO_OFFSET_RESET
              value: earliest
            - name: CONSUMER_BOOTSTRAP_SERVERS
              value: kafka0:9093
            - name: CONSUMER_GROUP_ID
              value: NotifierService
            - name: DATABASE_IP
              value: notifier-db
            - name: DATABASE_NAME
              value: Notifier
            - name: DATABASE_PASSWORD
              value: root
            - name: DATABASE_PORTA
              value: "3309"
            - name: DATABASE_USERNAME
              value: root
            - name: DOCKER_ENVIRONMENT
              value: "True"
            - name: GROUP_ID
              value: NotifierService
            - name: HEARTBEAT_FREQUENCY
              value: "10"
            - name: CLUSTER
              value: "0"
            - name: PARTITION
              value: "0"
            - name: PRODUCER_BOOTSTRAP_SERVERS
              value: kafka0:9093
            - name: PRODUCER_CLIENT_ID
              value: NotifierService
            - name: SLAMANAGER
              value: sla-manager
          image: mircoantona/weathereventnotifier:notifier-service-cluster0-part0
          name: notifier-service-cluster0-part0
          ports:
            - containerPort: 8086
              hostPort: 8086
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: "226492416"
      restartPolicy: Always
status: {}

---