apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.service: prometheus
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.network/microservices-network: "true"
        app.service: prometheus
    spec:
      containers:
        - args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.enable-lifecycle
          image: prom/prometheus
          name: prometheus-service
          ports:
            - containerPort: 9090
              hostPort: 9090
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: '216M'
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prometheus-config
      restartPolicy: Always
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
status: {}
