---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: scheduler-db
  name: scheduler-db
spec:
  ports:
    - name: "3310"
      port: 3310
      targetPort: 3306
  selector:
    app.service: scheduler-db
status:
  loadBalancer: {}

---
