---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: scheduler-service-cluster0-part0
  name: scheduler-service-cluster0-part0
spec:
  ports:
    - name: "8087"
      port: 8087
      targetPort: 8087
  selector:
    io.kompose.service: scheduler-service-cluster0-part0
status:
  loadBalancer: {}

---
