---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: sla-manager
  name: sla-manager
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app.service: sla-manager
status:
  loadBalancer: {}

---