---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: sla-manager-db
  name: sla-manager-db
spec:
  ports:
    - name: "1434"
      port: 1434
      targetPort: 1433
  selector:
    app.service: sla-manager-db
status:
  loadBalancer: {}

---