---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: telegram-service-cluster0-part0
  name: telegram-service-cluster0-part0
spec:
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8088
  selector:
    app.service: telegram-service-cluster0-part0
status:
  loadBalancer: {}

---