---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: telegram-db
  name: telegram-db
spec:
  ports:
    - name: "3311"
      port: 3311
      targetPort: 3306
  selector:
    io.kompose.service: telegram-db
status:
  loadBalancer: {}

---