---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: expose-api-db
  name: expose-api-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: expose-api-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/microservices-network: "true"
        io.kompose.service: expose-api-db
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: Express
            - name: SA_PASSWORD
              value: RootRoot.1
          image: mcr.microsoft.com/mssql/server
          name: expose-api-db
          ports:
            - containerPort: 1433
              hostPort: 1433
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /var/opt/mssql
              name: userdata-database
      restartPolicy: Always
      volumes:
        - name: userdata-database
          persistentVolumeClaim:
            claimName: userdata-database
status: {}

---