---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: expose-api-db
  name: expose-api-db
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    app.service: expose-api-db
status:
  loadBalancer: {}

---