---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: weather-db
  name: weather-db
spec:
  ports:
    - name: "3312"
      port: 3312
      targetPort: 3306
  selector:
    app.service: weather-db
status:
  loadBalancer: {}

---
