---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: zookeeper0
  name: zookeeper0
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.kompose.service: zookeeper0
status:
  loadBalancer: {}

---