---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.service: zookeeper0
  name: zookeeper0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: zookeeper0
  strategy: {}
  template:
    metadata:
      labels:
        app.network/microservices-network: "true"
        app.service: zookeeper0
    spec:
      containers:
        - image: wurstmeister/zookeeper:latest
          name: zookeeper0
          ports:
            - containerPort: 2181
              hostPort: 2181
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: '216M'
      restartPolicy: Always
status: {}