{
 "title": "Http",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "http_request_duration_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_requests_received_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "http_requests_received_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "http_requests_in_progress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "__auto" }
   ]
  }
 ]
}