---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: expose-api
  name: expose-api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: expose-api
status:
  loadBalancer: {}

---