---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mail-service-part0
  name: mail-service-part0
spec:
  ports:
    - name: "8085"
      port: 8085
      targetPort: 8085
  selector:
    io.kompose.service: mail-service-part0
status:
  loadBalancer: {}

---