---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: telegram-service-part0
  name: telegram-service-part0
spec:
  ports:
    - name: "8088"
      port: 8088
      targetPort: 8088
  selector:
    io.kompose.service: telegram-service-part0
status:
  loadBalancer: {}

---