---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: weather-service-part0
  name: weather-service-part0
spec:
  ports:
    - name: "8089"
      port: 8089
      targetPort: 8089
  selector:
    io.kompose.service: weather-service-part0
status:
  loadBalancer: {}

---
