---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mail-db-part0
  name: mail-db-part0
spec:
  ports:
    - name: "3308"
      port: 3308
      targetPort: 3306
  selector:
    io.kompose.service: mail-db-part0
status:
  loadBalancer: {}

---