---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: scheduler-db-part0
  name: scheduler-db-part0
spec:
  ports:
    - name: "3310"
      port: 3310
      targetPort: 3306
  selector:
    io.kompose.service: scheduler-db-part0
status:
  loadBalancer: {}

---
