---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: weather-db-part0
  name: weather-db-part0
spec:
  ports:
    - name: "3312"
      port: 3312
      targetPort: 3306
  selector:
    io.kompose.service: weather-db-part0
status:
  loadBalancer: {}

---
