---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: configurator-service-cluster0-part1
  name: configurator-service-cluster0-part1
spec:
  ports:
    - name: "8090"
      port: 8090
      targetPort: 8090
  selector:
    app.service: configurator-service-cluster0-part1
status:
  loadBalancer: {}

---
