---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mail-service-cluster0-part1
  name: mail-service-cluster0-part1
spec:
  ports:
    - name: "8091"
      port: 8091
      targetPort: 8091
  selector:
    io.kompose.service: mail-service-cluster0-part1
status:
  loadBalancer: {}

---