---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: notifier-service-cluster0-part1
  name: notifier-service-cluster0-part1
spec:
  ports:
    - name: "8092"
      port: 8092
      targetPort: 8092
  selector:
    app.service: notifier-service-cluster0-part1
status:
  loadBalancer: {}

---