---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: scheduler-service-cluster0-part1
  name: scheduler-service-cluster0-part1
spec:
  ports:
    - name: "8093"
      port: 8093
      targetPort: 8093
  selector:
    app.service: scheduler-service-cluster0-part1
status:
  loadBalancer: {}

---
