---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: telegram-service-cluster0-part1
  name: telegram-service-cluster0-part1
spec:
  ports:
    - name: "8094"
      port: 8094
      targetPort: 8094
  selector:
    io.kompose.service: telegram-service-cluster0-part1
status:
  loadBalancer: {}

---