---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.service: weather-service-cluster0-part1
  name: weather-service-cluster0-part1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: weather-service-cluster0-part1
  strategy: {}
  template:
    metadata:
      labels:
        app.network/microservices-network: "true"
        app.service: weather-service-cluster0-part1
    spec:
      containers:
        - env:
            - name: CONSUMER_AUTO_OFFSET_RESET
              value: earliest
            - name: CONSUMER_BOOTSTRAP_SERVERS
              value: kafka0:9093
            - name: CONSUMER_GROUP_ID
              value: WeatherService
            - name: DATABASE_IP
              value: weather-db
            - name: DATABASE_NAME
              value: Weather
            - name: DATABASE_PASSWORD
              value: root
            - name: DATABASE_PORTA
              value: "3312"
            - name: DATABASE_USERNAME
              value: root
            - name: DISTANCE_REUSE_WEATHER_KM
              value: "5"
            - name: DOCKER_ENVIRONMENT
              value: "True"
            - name: GROUP_ID
              value: WeatherService
            - name: HEARTBEAT_FREQUENCY
              value: "10"
            - name: CLUSTER
              value: "0"
            - name: PARTITION
              value: "1"
            - name: PRODUCER_BOOTSTRAP_SERVERS
              value: kafka0:9093
            - name: PRODUCER_CLIENT_ID
              value: WeatherService
            - name: SLAMANAGER
              value: sla-manager
          image: mircoantona/weathereventnotifier:weather-service-cluster0-part1
          name: weather-service-cluster0-part1
          ports:
            - containerPort: 8095
              hostPort: 8095
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: '216M'
      restartPolicy: Always
status: {}

---
