---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: weather-service-cluster0-part1
  name: weather-service-cluster0-part1
spec:
  ports:
    - name: "8095"
      port: 8095
      targetPort: 8095
  selector:
    io.kompose.service: weather-service-cluster0-part1
status:
  loadBalancer: {}

---
