---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: configurator-service-cluster1-part0
  name: configurator-service-cluster1-part0
spec:
  ports:
    - name: "8101"
      port: 8101
      targetPort: 8101
  selector:
    app.service: configurator-service-cluster1-part0
status:
  loadBalancer: {}

---
