---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: kafka1
  name: kafka1
spec:
  ports:
    - name: "9094"
      port: 9094
      targetPort: 9094
  selector:
    app.service: kafka1
status:
  loadBalancer: {}

---