---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: mail-service-cluster1-part0
  name: mail-service-cluster1-part0
spec:
  ports:
    - name: "8100"
      port: 8100
      targetPort: 8100
  selector:
    app.service: mail-service-cluster1-part0
status:
  loadBalancer: {}

---