---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: notifier-service-cluster1-part1
  name: notifier-service-cluster1-part1
spec:
  ports:
    - name: "8105"
      port: 8105
      targetPort: 8105
  selector:
    io.kompose.service: notifier-service-cluster1-part1
status:
  loadBalancer: {}

---