---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: notifier-service-cluster1-part0
  name: notifier-service-cluster1-part0
spec:
  ports:
    - name: "8099"
      port: 8099
      targetPort: 8099
  selector:
    app.service: notifier-service-cluster1-part0
status:
  loadBalancer: {}

---