---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: scheduler-service-cluster1-part1
  name: scheduler-service-cluster1-part1
spec:
  ports:
    - name: "8104"
      port: 8104
      targetPort: 8104
  selector:
    io.kompose.service: scheduler-service-cluster1-part1
status:
  loadBalancer: {}

---
