---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: scheduler-service-cluster1-part0
  name: scheduler-service-cluster1-part0
spec:
  ports:
    - name: "8098"
      port: 8098
      targetPort: 8098
  selector:
    app.service: scheduler-service-cluster1-part0
status:
  loadBalancer: {}

---
