---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: telegram-service-cluster1-part0
  name: telegram-service-cluster1-part0
spec:
  ports:
    - name: "8097"
      port: 8097
      targetPort: 8097
  selector:
    io.kompose.service: telegram-service-cluster1-part0
status:
  loadBalancer: {}

---