---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: weather-service-cluster1-part1
  name: weather-service-cluster1-part1
spec:
  ports:
    - name: "8102"
      port: 8102
      targetPort: 8102
  selector:
    app.service: weather-service-cluster1-part1
status:
  loadBalancer: {}

---
