---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: weather-service-cluster1-part0
  name: weather-service-cluster1-part0
spec:
  ports:
    - name: "8096"
      port: 8096
      targetPort: 8096
  selector:
    io.kompose.service: weather-service-cluster1-part0
status:
  loadBalancer: {}

---
