---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: zookeeper1
  name: zookeeper1
spec:
  ports:
    - name: "2182"
      port: 2182
      targetPort: 2181
  selector:
    app.service: zookeeper1
status:
  loadBalancer: {}

---