---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: zookeeper1
  name: zookeeper1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/microservices-network: "true"
        io.kompose.service: zookeeper1
    spec:
      containers:
        - image: wurstmeister/zookeeper:latest
          name: zookeeper1
          ports:
            - containerPort: 2181
              hostPort: 2182
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}