---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.service: zookeeper1
  name: zookeeper1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.service: zookeeper1
  strategy: {}
  template:
    metadata:
      labels:
        app.network/microservices-network: "true"
        app.service: zookeeper1
    spec:
      containers:
        - image: wurstmeister/zookeeper:latest
          name: zookeeper1
          ports:
            - containerPort: 2181
              hostPort: 2182
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: '216M'
      restartPolicy: Always
status: {}