version: '3'

services:
    
  expose-api-db:
    image: mcr.microsoft.com/mssql/server
    container_name: expose-api-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: RootRoot.1
      ACCEPT_EULA: Y
      MSSQL_PID: Express
    volumes:
      - userdata-database:/var/opt/mssql
    networks:
      - microservices-network
      
  expose-api:
    container_name: expose-api
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ConnectionStrings=Data Source=expose-api-db,1433;Initial Catalog=Userdata;User ID=sa;Password=RootRoot.1; Encrypt=False;
      - ConnectionStringsMaster=Data Source=expose-api-db,1433;User ID=sa;Password=RootRoot.1;Encrypt=False;
      - Jwt=c5eKUcbKfkzGq6HfpnFhP7/G2pgS3S++YH33ue/A5uc=
      - AllowedHosts=*
    depends_on:
      - expose-api-db
        
volumes:
  userdata-database:
    name: userdata-database
networks:
  microservices-network:
    name: microservices-network
