FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app
COPY . ./
RUN dotnet publish ExposeAPIService/ExposeAPI.csproj -c Release -o out/api
RUN dotnet publish EntityFramework/EntityFramework.csproj -c Release -o out/ef
FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app
COPY --from=build /app/out/api ./api
COPY --from=build /app/out/ef ./ef
COPY --from=build /app/ExposeAPIService/appsettings.json /app/appsettings.json
EXPOSE 80
ENTRYPOINT ["dotnet", "api/ExposeAPI.dll"]
